language: ruby
cache: bundler
matrix:
  include:
    - {os: osx, osx_image: xcode8.3}
    - {os: osx, osx_image: xcode9.2}
git:
  depth: 1
script: bundle exec rspec -f d -c
addons:
  code_climate:
    repo_token: b4206ed2b9443314c998e8909dfa31f0ed476ea5ab460b98e102cd20508ff564
after_success:
  - bundle exec codeclimate-test-reporter
  
